spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
